### ISSUE TITLE
Is it now possible to use A2lix with One To Many relations?

### ISSUE THREAD

**Issue by anacicconi** [a2lix/a2lix.github.com#18]
Hello,

The last time I worked with a2lix Translation, it wasn't possible to make translatable fields that has one to many relation with another entity. 

For example, I couldn't do one class User, another class Document and then have a translatable $documents property in my User class wich could be used to upload multiple documents. 

I had to do multiple fields with one to one relation, like $document1, $document2 and so on. 

Is this still an issue? I can't find the old issue in the repository anymore. Maybe it was closed because it was fixed?

Thanks.

**Comment by webda2l** [comment]
Hello,

https://github.com/a2lix/TranslationFormBundle/tree/3.x currently in development (with no progress recently due to time run) is more flexible with help of https://github.com/a2lix/AutoFormBundle to fit your needs. You can give it a try.

Otherwise, your issues are over there https://github.com/a2lix/TranslationFormBundle/issues?utf8=%E2%9C%93&q=author%3A%22anacicconi+%22+

**Comment by anacicconi** [comment]
Hi @webda2l, thanks for the tips and the link. I'lm gonna take a look at AutoFomBundle. Strange, I couldn't find the issues. Anyway, I'll close this one.
